from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, update
from app.models.assessments import Assessment, AssessmentQuestion, AssessmentAttempt, Certificate
from app.models.learning import SkillScore, Skill
from app.services.analytics import analytics_service
from app.integrations.cloudinary_client import cloudinary_client
from app.core.logging import logger
import uuid
from datetime import datetime
from typing import Dict

class AssessmentService:
    async def start_attempt(self, db: AsyncSession, learner_id: uuid.UUID, assessment_id: uuid.UUID):
        attempt = AssessmentAttempt(
            assessment_id=assessment_id,
            learner_id=learner_id
        )
        db.add(attempt)
        await db.commit()
        await db.refresh(attempt)
        
        # Fetch questions
        query = select(AssessmentQuestion).where(AssessmentQuestion.assessment_id == assessment_id).order_by(AssessmentQuestion.position)
        result = await db.execute(query)
        questions = result.scalars().all()
        
        return {
            "id": attempt.id,
            "assessment_id": attempt.assessment_id,
            "questions": [
                {
                    "id": q.id,
                    "question_text": q.question_text,
                    "question_type": q.question_type,
                    "options": q.options,
                    "position": q.position
                } for q in questions
            ]
        }

    async def list_assessments_by_course(self, db: AsyncSession, course_id: uuid.UUID):
        query = select(Assessment).where(Assessment.course_id == course_id, Assessment.is_active == True)
        result = await db.execute(query)
        return result.scalars().all()

    async def get_user_certificates(self, db: AsyncSession, user_id: uuid.UUID):
        from app.models.content import Course
        query = (
            select(Certificate, Course.title.label("course_title"))
            .join(Course, Certificate.course_id == Course.id)
            .where(Certificate.learner_id == user_id)
        )
        result = await db.execute(query)
        rows = result.all()
        return [
            {
                "id": row.Certificate.id,
                "course_title": row.course_title,
                "issued_at": row.Certificate.issued_at,
                "pdf_url": row.Certificate.pdf_url
            } for row in rows
        ]

    async def submit_attempt(self, db: AsyncSession, attempt_id: uuid.UUID, answers: Dict[uuid.UUID, str]):
        # 1. Fetch attempt and questions
        query = select(AssessmentAttempt).where(AssessmentAttempt.id == attempt_id)
        result = await db.execute(query)
        attempt = result.scalar_one()
        
        questions_query = select(AssessmentQuestion).where(AssessmentQuestion.assessment_id == attempt.assessment_id)
        q_result = await db.execute(questions_query)
        questions = q_result.scalars().all()
        
        # 2. Score logic
        total_points = sum(q.points for q in questions)
        earned_points = 0
        
        for q in questions:
            user_answer = answers.get(q.id)
            if user_answer and user_answer.strip().lower() == q.correct_answer.strip().lower():
                earned_points += q.points
        
        score_pct = (earned_points / total_points) * 100 if total_points > 0 else 0
        
        assessment_query = select(Assessment).where(Assessment.id == attempt.assessment_id)
        a_result = await db.execute(assessment_query)
        assessment = a_result.scalar_one()
        
        passed = score_pct >= assessment.pass_score
        
        # 3. Update attempt
        attempt.submitted_at = datetime.utcnow()
        attempt.score = score_pct
        attempt.passed = passed
        attempt.answers = {str(k): v for k, v in answers.items()}
        
        await db.commit()
        
        # 4. Handle Pass/Fail
        if passed:
            await analytics_service.track("assessment.passed", attempt.learner_id, "assessment_attempt", attempt.id)
            if assessment.assessment_type == "final":
                await self.issue_certificate(db, attempt.learner_id, assessment.course_id, attempt.id)
        else:
            await analytics_service.track("assessment.failed", attempt.learner_id, "assessment_attempt", attempt.id)
            
        return {
            "score": score_pct,
            "passed": passed,
            "attempt_id": attempt.id
        }

    async def issue_certificate(self, db: AsyncSession, learner_id: uuid.UUID, course_id: uuid.UUID, attempt_id: uuid.UUID):
        # 1. Generate local PDF (logic placeholder)
        verification_id = uuid.uuid4()
        
        # 2. Upload to Cloudinary
        # For MVP, we pass the placeholder or generated bytes to cloudinary
        pdf_url = cloudinary_client.upload_certificate(
            b"%PDF-1.4 placeholder content", # In real impl, use WeasyPrint output
            public_id=str(verification_id)
        )
        
        cert = Certificate(
            learner_id=learner_id,
            course_id=course_id,
            attempt_id=attempt_id,
            verification_id=verification_id,
            pdf_url=pdf_url
        )
        db.add(cert)
        await db.commit()
        await analytics_service.track("certificate.issued", learner_id, "certificate", cert.id)
        return cert

assessment_service = AssessmentService()
